apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: dvsavenkov/hipster-frontend:0.1
    name: frontend
    resources: {}
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "product-catalog-service:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currency-service:7000"
      - name: CART_SERVICE_ADDR
        value: "cart-service:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendation-service:8080"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkout-service:5050"
      - name: SHIPPING_SERVICE_ADDR
        value: "shipping-service:50051"
      - name: AD_SERVICE_ADDR
        value: "ad-service:9555"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
